version: '3'

services:

  grpc-tube-db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=grpc_tube
      - POSTGRES_PASSWORD=grpc_tube
      - POSTGRES_DB=grpc_tube
    ports:
      - "5432:5432"

  grpc-tube:
    image: ddato/grpc-tube:latest
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://grpc_tube:grpc_tube@grpc-tube-db:5432/grpc_tube?sslmode=disable
    depends_on:
      - grpc-tube-db
