// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type User struct {
	ID             int64  `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashed_password"`
	Email          string `json:"email"`
}
